language: android

sudo: required
dist: precise

jdk: oraclejdk8

android:
 components:
    # latest version of the tools
    - tools
    - platform-tools

    # build tools version
    - build-tools-25.0.0

    # The SDK Version
    - android-22
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository